### ISSUE TITLE
Design fix (homepage-web): Dead whitespace where footer normally lives

### ISSUE THREAD

**Issue by meeglosh** [gamblefi/Gamebit#117]
When resizing the browser window, there appears a block of white space where the footer normally lives. We need to background image to always fill 100% of the screen (no white space).

Screen shot of current build, bottom section only:

![image](https://user-images.githubusercontent.com/11077445/151885016-0e988cc5-0bbc-4856-985a-ae9a96ec0727.png)

**Comment by ziad-saab** [comment]
Fixed by #127
