### ISSUE TITLE
Design fix (avalotto-web): Dead whitespace where footer normally lives

### ISSUE THREAD

**Issue by meeglosh** [gamblefi/Gamebit#118]
There's dead whitespace at the bottom of the avalotto game. The degen gradient should fill 100% of the screen.

Screen shot of the current build, bottom section only:

![image](https://user-images.githubusercontent.com/11077445/151886813-5bd96ba9-7d2c-446e-9547-3099c1e6a62b.png)

**Comment by ziad-saab** [comment]
Fixed by #127
